### ISSUE TITLE
Errors with netTKAnalysis.py

### ISSUE THREAD

**Issue by spirrello** [Owlz/NetTK#3]
Hi,

When running netTKAnalysis.py I'm getting the following error.  Any idea why?  I followed the installation instructions and am still getting this.  I am using Ubuntu 14.04.1.

spirrello@ubuntu:~/NetTK$ python ./netTKAnalysis.py
Press Enter To Exit

Process Process-1:
Traceback (most recent call last):
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "analysis/lineGraph.py", line 161, in lineGraphRun
  File "analysis/pieChart.py", line 126, in pieChartRun
    buildGraph()
    buildGraph()
  File "analysis/lineGraph.py", line 56, in buildGraph
    fig,ax = plt.subplots(nrows=len(plots), ncols=1, sharex=sharex, sharey=sharey)
  File "analysis/pieChart.py", line 31, in buildGraph
    fig = plt.figure()
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 1046, in subplots
    fig = figure(**fig_kw)
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    window = Tk.Tk()
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable
TclError: no display name and no $DISPLAY environment variable

**Comment by Owlz** [comment]
Sorry for the late reply. To me that looks like you're ssh-ing into a box to run that and haven't forwarded your X Display properly.

See this: http://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-from-ubuntu-machine
